### ISSUE TITLE
RAM-Usage

### ISSUE THREAD

**Issue by andi936** [aikopras/AP_DCC_library#7]
Dear Aiko,
thanks a lot for this great project, it's really much more easier in usage in comparison to other known libs. But there is one question I'd like to ask you: do you see a chance to reduce RAM-usage of the project? I'm working on a huge UNO-Projekt (R3), so every byte counts. I'd like to use AP_DCC_library instead of an other well know lib, which is difficult in usage, but RAM-usage there is significantly less.
Thanks in advance for your feedback,
kind regards, Andreas

**Comment by aikopras** [comment]
Dear Andreas
Thanks for your nice feedback.
Reducing code size would be relatively easy if you remove the functionality that you don't need. But I don't know what is needed, and what not. If, for example, you are only interested in Accessory functionalities, the Loco (Multi-function) functionality can be removed. DO you need PoM functionality? Do you need the myMaster option? There is not a "magic thing" that eats all the RAM, and that can easily be removed.

What you can do, is get an impression of the memory requirements by looking at (if I remember well) the .lst file that the compiler can generate. There are a couple of sites on the web that give various tips.
Bye, Aiko

**Comment by andi936** [comment]
Hello Aiko,
super-fast feedback, thank you very much. I only need accessories, maybe CV, just POM, that's all. I will test it with your advice, thanks for the quick help!
Best regards, Andreas
