### ISSUE TITLE
Accessory Decoder, Position-Value

### ISSUE THREAD

**Issue by andi936** [aikopras/AP_DCC_library#8]
Hello Aiko,
I noticed one more point: I suspect that the display of the position value for turnouts needs to be corrected. 
In “src/AP_DCC_library.h” in the definition of the class “Accessory” (line 189): 

    uint8_t position; // 0..1 - The turnout position (straight-curved, green-red, -/+)

Analogous to this in “examples/Accessory-Serial_monitor/Accessory-Serial_monitor.ino” in line 67

    if (accCmd.position == 1) Serial.println(“ +”);

I suspect that this is wrong. I have searched various sources and also made tests with the Z21 with Multimaus and WLAN-Maus, ESU Lokprogrammer and also Rocrail at Z21. The result is always the same: the position value 0 stands for “curved” (red), the value 1 for “straight” (green).

https://www.opendcc.de/info/dcc/dcc.html (unfortunately only in German) describes this clearly in chapter "Zubehörbefehle, Einfaches Format" (translated: "Accessory Commands, Simple Format"): 
    german original: "C=0 soll dabei Weiche auf Abzweig bzw. Signal auf Halt kennzeichnen"
    translated: “C=0 should indicate turnout to curved or signal to stop”. 

In AP_DCC_library.h line 189 would have to be changed to
    // 0..1 - The turnout position (curved-straigt, red-green, +/-)
or more unmistakable
    // 0..1 - The turnout position (0: curved/red/+, 1: straight/green/-)

in “examples/Accessory-Serial_monitor/Accessory-Serial_monitor.ino”, line 67 would have to be changed to
    if (accCmd.position == 0) Serial.println(” +"); 

I am looking forward to your feedback and your opinion,

best regards, Andreas

**Comment by aikopras** [comment]
Dear Andreas

I think you are right. Thanks for spotting this. Also RCN 213 says: "Bei Standardanwendungen bedeutet R = 0
Weiche auf Abzweig oder Fahrtrichtung links bzw. Signal auf Halt und R = 1 Weiche gerade oder Fahrtrichtung rechts bzw. Signal auf Fahrt." (German is no problem, I live 3 Km from the German border away ;-))

 I expect I will be able to update this in the next few days. Again, great that you found this! Much appreciated.
Bye, Aiko

**Comment by andi936** [comment]
Hello Aiko,
thanks a lot for your feedback. I'm looking forwared for the next version. Also thanks to the hint to RCN 213!

All the best, Andreas

**Comment by aikopras** [comment]
Dear Andreas

I think we agree that 0 = curved / red and 1 = straight / green. 
I agree that this could be written clearer on AP_DCC_library.h line 189.

However, as far as I checked, I couldn't find which positions + and - represent.
My LH100 seems to map + on **1**, and green on 1. Therefore, line 67 examples/Accessory-Serial_monitor/Accessory-Serial_monitor.ino” would be OK.

So the issue is what exactly + and - represent. What do you think?

Bye, Aiko

**Comment by andi936** [comment]
Hello Aiko,

In my opinion, it is correct if “+” stands for curved (=0 / =red) and “-” for straight. 

The “+” and “-” in the LH100 probably result from a display deficit of the used LCD display. As far as I can see, it is not possible to display a diagonal line at the point where the turnout position is displayed (the Multimaus from Roco/Fleischmann has a different solution, the LCD display has a graphic symbol for the turnout position). Lenz solves this with the display of “+” and “-” and thus, in my opinion, logically “+” for curved. This makes the “-” look like a “straight position”.

All the best, Andreas

**Comment by aikopras** [comment]
Dear Andreas

I've checked it with Lenz LH100, LH101 and RocoMouse. The conclusion is that:
0 = red / diverging (RocoMouse) / - (LH10X)
1 = green / straight (RocoMouse) / + (LH10X)

If the + and - on the Lenz LH10X are logical or not, is debatable (I tend to agree with your view). However, the examples should represent what Lenz is doing, and not what we would have liked Lenz to do.

I have updated some text (overview page, example and AP_DCC_library.h line 189.

Thanks. Aiko

**Comment by andi936** [comment]
Hello Aiko,

thank you very much for your feedback and the changes! May I ask you one thing: In your last answer you wrote that your LH100 shows + on curved, but your test has now shown that + is displayed on straight. Is that correct? I just wanted a quick check to make sure there was no confusion.

Thanks again for your efforts,
Have a nice day, Andreas

**Comment by aikopras** [comment]
Hi Andreas

Thanks for spotting this. I made a typo in an earlier  message and just corrected it.

Bye, Aiko.

**Comment by andi936** [comment]
Hi Aiko,

thanks for all your effort. I think, the issue can be closed with this. I'm looking forward to your new release here on GITHUB. I wish you a merry christmas and a good start into the New Year!

All the best, Andreas
